# Generated by Django 4.0.1 on 2022-01-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
