# Generated by Django 4.0.1 on 2022-01-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_driver_car_number_driver_car_type_driver_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_start_time']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_finish_time',
        ),
    ]
