# Generated by Django 4.0.1 on 2022-01-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_remove_order_order_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_number',
        ),
    ]
