# Generated by Django 4.0.1 on 2022-01-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_driver_car_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_start_time']},
        ),
    ]
